### ISSUE TITLE
Example of using getTrampoline?

### ISSUE THREAD

**Issue by qb-0** [ba0f3/subhook.nim#1]
Hey,

thank you for that bindings. I was pretty surprised that a hooking library is done in nim. =)

So using it with the usual detour works fine:
```
UserCode
hook.remove()
originalProc()
hook.install()
```

But once I try to use the trampoline it crashes for me. Im injecting a library into another process. My attempt was:
```
UserCode
cast[typeof(originalProc)](hook.getTrampoline())(args)
```

**Comment by ba0f3** [comment]
`getTrampoline` is working fine, please make sure you are hooking to correct address,  calling convention
