### ISSUE TITLE
Crashing process

### ISSUE THREAD

**Issue by woidptr** [ba0f3/subhook.nim#3]
Hello, I am having this issue when trying to hook keyboard input in the game (using dll injection).

Here is my code:
```nim
import winim
import subhook

type KeymapHook = proc(key: UINT_PTR, held: bool) {.thiscall.}

var keymapHook*: Hook

proc keymapDetour(key: UINT_PTR, held: bool) = 
    cast[KeymapHook](keymapHook.getTrampoline())(key, held)

proc initKeyboardHook() = 
    var baseAddr = GetModuleHandleA("Minecraft.Windows.exe")
    keymapHook = initHook(
        cast[pointer](baseAddr + 0x1BE780),
        cast[pointer](cast[ByteAddress](keymapDetour)),
        true,
        SUBHOOK_64BIT_OFFSET
    )
```

When the dll injected, everything is working fine, which means that dll initialization was successful.
Game is crashing when the key on the keyboard is pressed. And btw, when detour function is empty, keyboard is not working, which means the hook address is right.
There is something wrong when calling the original function to unlock the keyboard.

**Comment by ba0f3** [comment]
`keymapDetour` should use `thiscall` calling convention too

**Comment by woidptr** [comment]
> `keymapDetour` should use `thiscall` calling convention too

No, this is not the issue. Process is still crashing.

**Comment by woidptr** [comment]
Just as an example that this is possible, here is my cpp code that works as expected:
```cpp
typedef void(*KeymapHook)(uintptr_t, bool);
KeymapHook oKeymap;

void KeymapDetour(uintptr_t key, bool held) {
    return oKeymap(key, held);
}

void KeyboardHook::init() {
    uintptr_t hookAddr = (uintptr_t)GetModuleHandleA("Minecraft.Windows.exe") + 0x1B6B00;

    MH_CreateHook((void*)hookAddr, &KeymapDetour, reinterpret_cast<LPVOID*>(&oKeymap));
    MH_EnableHook((void*)hookAddr);
}
```

**Comment by ba0f3** [comment]
can you do it w/ subhook in cpp?

**Comment by woidptr** [comment]
I wasn't able to test cpp code with subhook, because I failed to install it. But I know that the same issue occurs when using minhook with nim.
```nim
import winim
import subhook
import minhook

type KeymapHook = proc(key: UINT_PTR, held: bool) {.thiscall.}
var oKeymap: KeymapHook

proc keymapDetour(key: UINT_PTR, held: bool) {.thiscall.} = 
    oKeymap(key, held)

proc initKeyboardHook() = 
    var baseAddr = GetModuleHandleA("Minecraft.Windows.exe")
    var hookAddress = cast[pointer](baseAddr + 0x1BE780)
    assert createHook(hookAddress, keymapDetour, cast[ptr pointer](oKeymap)) == mhOk
    enableHook(hookAddress)
```

**Comment by ba0f3** [comment]
So I think problem doesn't relate to subhook itself.
But I want to digging deeper into this,  can you send me the disassembly of the function you want to hook? and crash dump maybe?

**Comment by woidptr** [comment]
![image](https://user-images.githubusercontent.com/62186908/198990233-252870e0-23b6-469f-b2d8-f763dc3720e7.png)
Here is the disassembly of the keymap function

**Comment by ba0f3** [comment]
I don't think this function uses thiscall calling convetion

**Comment by woidptr** [comment]
Well, in cpp it works with no calling convention, stdcall and thiscall

**Comment by ba0f3** [comment]
try again with `cdecl` instead of `thiscall`

**Comment by woidptr** [comment]
Not working... Maybe there is some restrictions that nim breaks? Because Minecraft is a UWP app which has a bunch of restrictions such as you cannot allocate console or make message popup in there.

**Comment by woidptr** [comment]
Also, why subhook is doing this
![image](https://user-images.githubusercontent.com/62186908/198994652-da7bd310-516c-4498-9e41-f92a9821134c.png)
Instead of this (how minhook does it)
![image](https://user-images.githubusercontent.com/62186908/198994986-ed0d4ab3-3176-46e8-9697-bdd7da21a3ee.png)

**Comment by ba0f3** [comment]
I'm sorry but I have no idea, you can try to ask @Zeex in https://github.com/Zeex/subhook

**Comment by 4zv4l** [comment]
I also had the issue with minhook which made me arrive here, any solution found ?

**Comment by ba0f3** [comment]
A limitation added to subhook's README recently, it may related to your issues https://github.com/Zeex/subhook/commit/4f173b23239c017a9f3e53364fe371975aca2321

**Comment by ba0f3** [comment]
A limitation added to subhook's README recently, it may related to your issues https://github.com/Zeex/subhook/commit/4f173b23239c017a9f3e53364fe371975aca2321
